[supervisord]
nodaemon=true

[program:php-fpm]
command=/usr/local/sbin/php-fpm
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm.log
stderr_logfile=/var/log/php-fpm_err.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx_access.log
stderr_logfile=/var/log/nginx_error.log

[program:laravel-worker]
command=php /var/www/artisan queue:work --sleep=3 --tries=3
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/laravel-worker.log


[program:laravel-scheduler]
command=bash -c "while true; do php /var/www/artisan schedule:run >> /dev/null 2>&1; sleep 60; done"
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/laravel-scheduler.log

# Ensure the log files are writable by www-data
[program:setup-permissions]
command=bash -c "touch /var/log/laravel-worker.log /var/log/laravel-scheduler.log && chmod 664 /var/log/laravel-worker.log /var/log/laravel-scheduler.log && chown www-data:www-data /var/log/laravel-worker.log /var/log/laravel-scheduler.log"
autostart=true
autorestart=false
startsecs=0
priority=1
