version: '3.8'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - admin_db
  admin_db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: internal
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pass
      MYSQL_ROOT_PASSWORD: user_pass
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 6604:3306
