<?php

return [
    'permissions' => [
        // User module permissions
        'USER_VIEW' => 'users.user.view',
        'USER_LIST' => 'users.user.list',
        'USER_CREATE' => 'users.user.create',
        'USER_EDIT' => 'users.user.edit',
        'USER_DELETE' => 'users.user.delete',
        'USER_EXPORT' => 'users.user.export',
        'USER_IMPORT' => 'users.user.import',
        'USER_BULK_DELETE' => 'users.user.bulk-delete',
        'USER_ACTIVATE' => 'users.user.activate',
        'USER_DEACTIVATE' => 'users.user.deactivate',

        'CLIENT_VIEW' => 'users.client.view',
        'CLIENT_LIST' => 'users.client.list',
        'CLIENT_CREATE' => 'users.client.create',
        'CLIENT_EDIT' => 'users.client.edit',
        'CLIENT_DELETE' => 'users.client.delete',
        'CLIENT_EXPORT' => 'users.client.export',
        'CLIENT_IMPORT' => 'users.client.import',
        'CLIENT_BULK_DELETE' => 'users.client.bulk-delete',

        'BROKER_VIEW' => 'users.broker.view',
        'BROKER_LIST' => 'users.broker.list',
        'BROKER_CREATE' => 'users.broker.create',
        'BROKER_EDIT' => 'users.broker.edit',
        'BROKER_DELETE' => 'users.broker.delete',
        'BROKER_EXPORT' => 'users.broker.export',
        'BROKER_IMPORT' => 'users.broker.import',
        'BROKER_BULK_DELETE' => 'users.broker.bulk-delete',

        'EMPLOYEE_VIEW' => 'users.employee.view',
        'EMPLOYEE_LIST' => 'users.employee.list',
        'EMPLOYEE_CREATE' => 'users.employee.create',
        'EMPLOYEE_EDIT' => 'users.employee.edit',
        'EMPLOYEE_DELETE' => 'users.employee.delete',
        'EMPLOYEE_EXPORT' => 'users.employee.export',
        'EMPLOYEE_IMPORT' => 'users.employee.import',
        'EMPLOYEE_BULK_DELETE' => 'users.employee.bulk-delete',

        // User Profile module permissions
        'USER_PROFILE_DATA_VIEW' => 'user-profile.data.view',
        'USER_PROFILE_DATA_UPDATE' => 'user-profile.data.update',
        'USER_PROFILE_CONTACT_VIEW' => 'user-profile.contact.view',
        'USER_PROFILE_CONTACT_UPDATE' => 'user-profile.contact.update',
        'USER_PROFILE_IDENTITY_VIEW' => 'user-profile.identity.view',
        'USER_PROFILE_IDENTITY_UPDATE' => 'user-profile.identity.update',
        'PROFILE_PERSONAL_INFO_UPDATE' => 'user-profile.personal-information.update',
        'PROFILE_CONTACT_INFO_UPDATE' => 'user-profile.contact-information.update',
        'PROFILE_PASSPORT_INFO_UPDATE' => 'user-profile.passport-information.update',
        'PROFILE_BANK_INFO_CREATE' => 'user-profile.bank-information.create',
        'PROFILE_BANK_INFO_UPDATE' => 'user-profile.bank-information.update',
        'PROFILE_BANK_INFO_DELETE' => 'user-profile.bank-information.delete',
        'PROFILE_ADDRESS_INFO_UPDATE' => 'user-profile.address-information.update',
        'PROFILE_MARITAL_STATUS_CREATE' => 'user-profile.marital-status.create',
        'PROFILE_MARITAL_STATUS_UPDATE' => 'user-profile.marital-status.update',
        'PROFILE_MARITAL_STATUS_DELETE' => 'user-profile.marital-status.delete',
        'PROFILE_SOCIAL_MEDIA_UPDATE' => 'user-profile.social-media-account.update',
        'PROFILE_BORDER_NUMBER_UPDATE' => 'user-profile.border-number-information.update',
        'PROFILE_RESIDENCE_INFO_UPDATE' => 'user-profile.residence-information.update',
        'PROFILE_ABOUT_ME_UPDATE' => 'user-profile.about-me-information.update',
        'PROFILE_CV_UPDATE' => 'user-profile.cv.update',
        'PROFILE_JOB_OFFER_UPDATE' => 'user-profile.job-offer.update',
        'PROFILE_CONTRACT_WORK_UPDATE' => 'user-profile.contract-work.update',
        'PROFILE_EMPLOYMENT_INFO_UPDATE' => 'user-profile.employment-information.update',
        'PROFILE_SALARY_INFO_UPDATE' => 'user-profile.salary-information.update',
        'PROFILE_QUALIFICATION_CREATE' => 'user-profile.qualification.create',
        'PROFILE_QUALIFICATION_UPDATE' => 'user-profile.qualification.update',
        'PROFILE_QUALIFICATION_DELETE' => 'user-profile.qualification.delete',
        'PROFILE_EXPERIENCE_CREATE' => 'user-profile.experience.create',
        'PROFILE_EXPERIENCE_UPDATE' => 'user-profile.experience.update',
        'PROFILE_EXPERIENCE_DELETE' => 'user-profile.experience.delete',
        'PROFILE_COURSES_CREATE' => 'user-profile.courses.create',
        'PROFILE_COURSES_UPDATE' => 'user-profile.courses.update',
        'PROFILE_COURSES_DELETE' => 'user-profile.courses.delete',
        'PROFILE_CERTIFICATES_CREATE' => 'user-profile.certificates.create',
        'PROFILE_CERTIFICATES_UPDATE' => 'user-profile.certificates.update',
        'PROFILE_CERTIFICATES_DELETE' => 'user-profile.certificates.delete',
        'PROFILE_WORK_LICENSE_UPDATE' => 'user-profile.work-license.update',

        // Company module permissions
        'COMPANY_VIEW' => 'companies.company.view',
        'COMPANY_LIST' => 'companies.company.list',
        'COMPANY_CREATE' => 'companies.company.create',
        'COMPANY_EDIT' => 'companies.company.edit',
        'COMPANY_DELETE' => 'companies.company.delete',
        'COMPANY_LOGIN_AS_ADMIN' => 'companies.company.login-as-admin',
        'COMPANY_EXPORT' => 'companies.company.export',
        'COMPANY_IMPORT' => 'companies.company.import',
        'COMPANY_BULK_DELETE' => 'companies.company.bulk-delete',
        'COMPANY_ACTIVATE' => 'companies.company.activate',
        'COMPANY_DEACTIVATE' => 'companies.company.deactivate',

        // Role and Permission module permissions
        'ROLE_LIST' => 'settings.role.list',
        'ROLE_VIEW' => 'settings.role.view',
        'ROLE_CREATE' => 'settings.role.create',
        'ROLE_EDIT' => 'settings.role.edit',
        'ROLE_DELETE' => 'settings.role.delete',
        'ROLE_ASSIGN' => 'settings.role.assign',
        'ROLE_CLONE' => 'settings.role.clone',

        'PERMISSION_LIST' => 'settings.permission.list',
        'PERMISSION_CREATE' => 'settings.permission.create',
        'PERMISSION_EDIT' => 'settings.permission.edit',
        'PERMISSION_DELETE' => 'settings.permission.delete',
        'PERMISSION_VIEW' => 'settings.permission.view',
        'PERMISSION_ASSIGN' => 'settings.permission.assign',
        'IDENTIFIER_LIST' => 'settings.identifier.list',
        'LOGIN_WAY_CREATE' => 'settings.login-way.create',
        'LOGIN_WAY_UPDATE' => 'settings.login-way.update',
        'LOGIN_WAY_VIEW' => 'settings.login-way.view',
        'LOGIN_WAY_DELETE' => 'settings.login-way.delete',
        'LOGIN_WAY_ACTIVATE' => 'settings.login-way.activate',
        'COMPANY_PROFILE_VIEW' => 'settings.company-profile.view',
        'DRIVER_VIEW' => 'settings.driver.view',
        'DRIVER_UPDATE' => 'settings.driver.update',

        // Organization module permissions
        'ORGANIZATION_BRANCH_VIEW' => 'organization.branch.view',
        'ORGANIZATION_BRANCH_CREATE' => 'organization.branch.create',
        'ORGANIZATION_BRANCH_UPDATE' => 'organization.branch.update',
        'ORGANIZATION_BRANCH_DELETE' => 'organization.branch.delete',
        'ORGANIZATION_BRANCH_LIST' => 'organization.branch.list',
        'ORGANIZATION_BRANCH_EXPORT' => 'organization.branch.export',
        'ORGANIZATION_MANAGEMENT_VIEW' => 'organization.management.view',
        'ORGANIZATION_MANAGEMENT_CREATE' => 'organization.management.create',
        'ORGANIZATION_MANAGEMENT_UPDATE' => 'organization.management.update',
        'ORGANIZATION_MANAGEMENT_DELETE' => 'organization.management.delete',
        'ORGANIZATION_MANAGEMENT_LIST' => 'organization.management.list',
        'ORGANIZATION_MANAGEMENT_EXPORT' => 'organization.management.export',
        'ORGANIZATION_USERS_VIEW' => 'organization.users.view',
        'ORGANIZATION_USERS_LIST' => 'organization.users.list',
        'ORGANIZATION_JOB_TITLE_VIEW' => 'organization.job-title.view',
        'ORGANIZATION_JOB_TITLE_CREATE' => 'organization.job-title.create',
        'ORGANIZATION_JOB_TITLE_UPDATE' => 'organization.job-title.update',
        'ORGANIZATION_JOB_TITLE_DELETE' => 'organization.job-title.delete',
        'ORGANIZATION_JOB_TITLE_LIST' => 'organization.job-title.list',
        'ORGANIZATION_JOB_TITLE_ACTIVATE' => 'organization.job-title.activate',
        'ORGANIZATION_JOB_TITLE_EXPORT' => 'organization.job-title.export',
        'ORGANIZATION_JOB_TYPE_VIEW' => 'organization.job-type.view',
        'ORGANIZATION_JOB_TYPE_CREATE' => 'organization.job-type.create',
        'ORGANIZATION_JOB_TYPE_UPDATE' => 'organization.job-type.update',
        'ORGANIZATION_JOB_TYPE_DELETE' => 'organization.job-type.delete',
        'ORGANIZATION_JOB_TYPE_LIST' => 'organization.job-type.list',
        'ORGANIZATION_JOB_TYPE_ACTIVATE' => 'organization.job-type.activate',
        'ORGANIZATION_JOB_TYPE_EXPORT' => 'organization.job-type.export',

        // Company Profile module permissions
        'COMPANY_PROFILE_OFFICIAL_DATA_VIEW' => 'company-profile.official-data.view',
        'COMPANY_PROFILE_OFFICIAL_DATA_UPDATE' => 'company-profile.official-data.update',
        'COMPANY_PROFILE_OFFICIAL_DATA_REQUEST_UPDATE' => 'company-profile.official-data.request-update',
        'COMPANY_PROFILE_LEGAL_DATA_VIEW' => 'company-profile.legal-data.view',
        'COMPANY_PROFILE_LEGAL_DATA_LIST' => 'company-profile.legal-data.list',
        'COMPANY_PROFILE_LEGAL_DATA_UPDATE' => 'company-profile.legal-data.update',
        'COMPANY_PROFILE_LEGAL_DATA_CREATE' => 'company-profile.legal-data.create',
        'COMPANY_PROFILE_LEGAL_DATA_DELETE' => 'company-profile.legal-data.delete',
        'COMPANY_PROFILE_LEGAL_DATA_REQUEST_UPDATE' => 'company-profile.legal-data.request-update',
        'COMPANY_PROFILE_ADDRESS_VIEW' => 'company-profile.address.view',
        'COMPANY_PROFILE_ADDRESS_UPDATE' => 'company-profile.address.update',
        'COMPANY_PROFILE_ADDRESS_REQUEST_UPDATE' => 'company-profile.address.request-update',
        'COMPANY_PROFILE_BRANCH_LIST' => 'company-profile.branch.list',
        'COMPANY_PROFILE_BRANCH_VIEW' => 'company-profile.branch.view',
        'COMPANY_PROFILE_OFFICIAL_DOCUMENT_VIEW' => 'company-profile.official-document.view',
        'COMPANY_PROFILE_OFFICIAL_DOCUMENT_LIST' => 'company-profile.official-document.list',
        'COMPANY_PROFILE_OFFICIAL_DOCUMENT_CREATE' => 'company-profile.official-document.create',
        'COMPANY_PROFILE_OFFICIAL_DOCUMENT_UPDATE' => 'company-profile.official-document.update',
        'COMPANY_PROFILE_OFFICIAL_DOCUMENT_DELETE' => 'company-profile.official-document.delete',

        // Country module permissions
        'COUNTRY_VIEW' => 'country.country.view',
        'COUNTRY_LIST' => 'country.country.list',
        'COUNTRY_CREATE' => 'country.country.create',
        'COUNTRY_EDIT' => 'country.country.edit',
        'COUNTRY_DELETE' => 'country.country.delete',
        'COUNTRY_EXPORT' => 'country.country.export',
        'COUNTRY_IMPORT' => 'country.country.import',
        'COUNTRY_BULK_DELETE' => 'country.country.bulk-delete',

        'STATE_VIEW' => 'country.state.view',
        'STATE_LIST' => 'country.state.list',
        'STATE_CREATE' => 'country.state.create',
        'STATE_EDIT' => 'country.state.edit',
        'STATE_DELETE' => 'country.state.delete',
        'STATE_EXPORT' => 'country.state.export',
        'STATE_IMPORT' => 'country.state.import',
        'STATE_BULK_DELETE' => 'country.state.bulk-delete',

        'CITY_VIEW' => 'country.city.view',
        'CITY_LIST' => 'country.city.list',
        'CITY_CREATE' => 'country.city.create',
        'CITY_EDIT' => 'country.city.edit',
        'CITY_DELETE' => 'country.city.delete',
        'CITY_EXPORT' => 'country.city.export',
        'CITY_IMPORT' => 'country.city.import',
        'CITY_BULK_DELETE' => 'country.city.bulk-delete',
    ],

    // Permission metadata for enhanced management
    'permission_groups' => [
        'users' => [
            'label' => 'User Management',
            'description' => 'Permissions for managing users, clients, brokers, and employees',
            'icon' => 'users',
            'color' => '#3B82F6',
            'permissions' => [
                'user' => ['USER_VIEW', 'USER_LIST', 'USER_CREATE', 'USER_EDIT', 'USER_DELETE', 'USER_EXPORT', 'USER_IMPORT', 'USER_BULK_DELETE', 'USER_ACTIVATE', 'USER_DEACTIVATE'],
                'client' => ['CLIENT_VIEW', 'CLIENT_LIST', 'CLIENT_CREATE', 'CLIENT_EDIT', 'CLIENT_DELETE', 'CLIENT_EXPORT', 'CLIENT_IMPORT', 'CLIENT_BULK_DELETE'],
                'broker' => ['BROKER_VIEW', 'BROKER_LIST', 'BROKER_CREATE', 'BROKER_EDIT', 'BROKER_DELETE', 'BROKER_EXPORT', 'BROKER_IMPORT', 'BROKER_BULK_DELETE'],
                'employee' => ['EMPLOYEE_VIEW', 'EMPLOYEE_LIST', 'EMPLOYEE_CREATE', 'EMPLOYEE_EDIT', 'EMPLOYEE_DELETE', 'EMPLOYEE_EXPORT', 'EMPLOYEE_IMPORT', 'EMPLOYEE_BULK_DELETE'],
            ]
        ],
        'user-profile' => [
            'label' => 'User Profile',
            'description' => 'Permissions for managing user profile information',
            'icon' => 'user-circle',
            'color' => '#10B981',
        ],
        'companies' => [
            'label' => 'Company Management',
            'description' => 'Permissions for managing companies and corporate data',
            'icon' => 'building',
            'color' => '#F59E0B',
        ],
        'company-profile' => [
            'label' => 'Company Profile',
            'description' => 'Permissions for managing company profile and legal documents',
            'icon' => 'document-text',
            'color' => '#8B5CF6',
        ],
        'organization' => [
            'label' => 'Organization Structure',
            'description' => 'Permissions for managing organizational hierarchy and job positions',
            'icon' => 'office-building',
            'color' => '#EF4444',
        ],
        'settings' => [
            'label' => 'System Settings',
            'description' => 'Permissions for system configuration and role management',
            'icon' => 'cog',
            'color' => '#6B7280',
        ],
        'country' => [
            'label' => 'Location Management',
            'description' => 'Permissions for managing countries, states, and cities',
            'icon' => 'globe',
            'color' => '#06B6D4',
        ],
    ],

    // Permission hierarchies and dependencies
    'permission_hierarchies' => [
        'ADMIN' => ['*'], // Super admin access
        'MANAGER' => [
            'users.*',
            'companies.*.view',
            'companies.*.list',
            'company-profile.*',
            'organization.*',
        ],
        'SUPERVISOR' => [
            'users.*.view',
            'users.*.list',
            'companies.*.view',
            'organization.*.view',
        ],
        'USER' => [
            'user-profile.*',
            'companies.company.view',
        ],
    ],

    // Critical permissions that require extra confirmation
    'critical_permissions' => [
        'USER_DELETE',
        'USER_BULK_DELETE', 
        'COMPANY_DELETE',
        'COMPANY_BULK_DELETE',
        'ROLE_DELETE',
        'PERMISSION_DELETE',
        'COMPANY_LOGIN_AS_ADMIN',
    ],

    // Actions that can be applied to resources
    'actions' => [
        'view' => ['label' => 'View', 'description' => 'Can view the resource', 'color' => '#10B981'],
        'list' => ['label' => 'List', 'description' => 'Can list/browse resources', 'color' => '#3B82F6'],
        'create' => ['label' => 'Create', 'description' => 'Can create new resources', 'color' => '#F59E0B'],
        'edit' => ['label' => 'Edit', 'description' => 'Can modify existing resources', 'color' => '#8B5CF6'],
        'update' => ['label' => 'Update', 'description' => 'Can update existing resources', 'color' => '#8B5CF6'],
        'delete' => ['label' => 'Delete', 'description' => 'Can delete resources', 'color' => '#EF4444'],
        'export' => ['label' => 'Export', 'description' => 'Can export data', 'color' => '#06B6D4'],
        'import' => ['label' => 'Import', 'description' => 'Can import data', 'color' => '#84CC16'],
        'bulk-delete' => ['label' => 'Bulk Delete', 'description' => 'Can delete multiple resources at once', 'color' => '#DC2626'],
        'activate' => ['label' => 'Activate', 'description' => 'Can activate resources', 'color' => '#059669'],
        'deactivate' => ['label' => 'Deactivate', 'description' => 'Can deactivate resources', 'color' => '#D97706'],
        'assign' => ['label' => 'Assign', 'description' => 'Can assign resources to others', 'color' => '#7C3AED'],
        'clone' => ['label' => 'Clone', 'description' => 'Can duplicate resources', 'color' => '#0891B2'],
    ],
];
