<?php

return [
    'permissions' => [
        // User module permissions
        'USER_VIEW' => 'users.user.view',
        'USER_LIST' => 'users.user.list',
        'USER_CREATE' => 'users.user.create',
        'USER_EDIT' => 'users.user.update',
        'USER_DELETE' => 'users.user.delete',
        'USER_EXPORT' => 'users.user.export',

        'CLIENT_VIEW' => 'users.client.view',
        'CLIENT_LIST' => 'users.client.list',
        'CLIENT_CREATE' => 'users.client.create',
        'CLIENT_EDIT' => 'users.client.update',
        'CLIENT_DELETE' => 'users.client.delete',
        'CLIENT_EXPORT' => 'users.client.export',

        'BROKER_VIEW' => 'users.broker.view',
        'BROKER_LIST' => 'users.broker.list',
        'BROKER_CREATE' => 'users.broker.create',
        'BROKER_EDIT' => 'users.broker.update',
        'BROKER_DELETE' => 'users.broker.delete',
        'BROKER_EXPORT' => 'users.broker.export',

        'EMPLOYEE_VIEW' => 'users.employee.view',
        'EMPLOYEE_LIST' => 'users.employee.list',
        'EMPLOYEE_CREATE' => 'users.employee.create',
        'EMPLOYEE_EDIT' => 'users.employee.update',
        'EMPLOYEE_DELETE' => 'users.employee.delete',
        'EMPLOYEE_EXPORT' => 'users.employee.export',

        // User Profile module permissions
        'USER_PROFILE_DATA_VIEW' => 'user-profile.data.view',
        'USER_PROFILE_DATA_UPDATE' => 'user-profile.data.update',
        'USER_PROFILE_CONTACT_VIEW' => 'user-profile.contact.view',
        'USER_PROFILE_CONTACT_UPDATE' => 'user-profile.contact.update',
        'USER_PROFILE_IDENTITY_VIEW' => 'user-profile.identity.view',
        'USER_PROFILE_IDENTITY_UPDATE' => 'user-profile.identity.update',
        'PROFILE_PERSONAL_INFO_VIEW' => 'user-profile.personal-information.view',
        'PROFILE_PERSONAL_INFO_UPDATE' => 'user-profile.personal-information.update',
        'PROFILE_CONTACT_INFO_VIEW' => 'user-profile.contact-information.view',
        'PROFILE_CONTACT_INFO_UPDATE' => 'user-profile.contact-information.update',
        'PROFILE_PASSPORT_INFO_VIEW' => 'user-profile.passport-information.view',
        'PROFILE_PASSPORT_INFO_UPDATE' => 'user-profile.passport-information.update',
        'PROFILE_BANK_INFO_VIEW' => 'user-profile.bank-information.view',
        'PROFILE_BANK_INFO_CREATE' => 'user-profile.bank-information.create',
        'PROFILE_BANK_INFO_UPDATE' => 'user-profile.bank-information.update',
        'PROFILE_BANK_INFO_DELETE' => 'user-profile.bank-information.delete',
        'PROFILE_ADDRESS_INFO_VIEW' => 'user-profile.address-information.view',
        'PROFILE_ADDRESS_INFO_UPDATE' => 'user-profile.address-information.update',
        'PROFILE_MARITAL_STATUS_VIEW' => 'user-profile.marital-status.view',
        'PROFILE_MARITAL_STATUS_CREATE' => 'user-profile.marital-status.create',
        'PROFILE_MARITAL_STATUS_UPDATE' => 'user-profile.marital-status.update',
        'PROFILE_MARITAL_STATUS_DELETE' => 'user-profile.marital-status.delete',
        'PROFILE_SOCIAL_MEDIA_VIEW' => 'user-profile.social-media-account.view',
        'PROFILE_SOCIAL_MEDIA_UPDATE' => 'user-profile.social-media-account.update',
        'PROFILE_BORDER_NUMBER_VIEW' => 'user-profile.border-number-information.view',
        'PROFILE_BORDER_NUMBER_UPDATE' => 'user-profile.border-number-information.update',
        'PROFILE_RESIDENCE_INFO_VIEW' => 'user-profile.residence-information.view',
        'PROFILE_RESIDENCE_INFO_UPDATE' => 'user-profile.residence-information.update',
        'PROFILE_ABOUT_ME_VIEW' => 'user-profile.about-me-information.view',
        'PROFILE_ABOUT_ME_UPDATE' => 'user-profile.about-me-information.update',
        'PROFILE_CV_VIEW' => 'user-profile.cv.view',
        'PROFILE_CV_UPDATE' => 'user-profile.cv.update',
        'PROFILE_JOB_OFFER_VIEW' => 'user-profile.job-offer.view',
        'PROFILE_JOB_OFFER_UPDATE' => 'user-profile.job-offer.update',
        'PROFILE_CONTRACT_WORK_VIEW' => 'user-profile.contract-work.view',
        'PROFILE_CONTRACT_WORK_UPDATE' => 'user-profile.contract-work.update',
        'PROFILE_EMPLOYMENT_INFO_VIEW' => 'user-profile.employment-information.view',
        'PROFILE_EMPLOYMENT_INFO_UPDATE' => 'user-profile.employment-information.update',
        'PROFILE_SALARY_INFO_VIEW' => 'user-profile.salary-information.view',
        'PROFILE_SALARY_INFO_UPDATE' => 'user-profile.salary-information.update',
        'PROFILE_QUALIFICATION_VIEW' => 'user-profile.qualification.view',
        'PROFILE_QUALIFICATION_CREATE' => 'user-profile.qualification.create',
        'PROFILE_QUALIFICATION_UPDATE' => 'user-profile.qualification.update',
        'PROFILE_QUALIFICATION_DELETE' => 'user-profile.qualification.delete',
        'PROFILE_EXPERIENCE_VIEW' => 'user-profile.experience.view',
        'PROFILE_EXPERIENCE_CREATE' => 'user-profile.experience.create',
        'PROFILE_EXPERIENCE_UPDATE' => 'user-profile.experience.update',
        'PROFILE_EXPERIENCE_DELETE' => 'user-profile.experience.delete',
        'PROFILE_COURSES_VIEW' => 'user-profile.courses.view',
        'PROFILE_COURSES_CREATE' => 'user-profile.courses.create',
        'PROFILE_COURSES_UPDATE' => 'user-profile.courses.update',
        'PROFILE_COURSES_DELETE' => 'user-profile.courses.delete',
        'PROFILE_CERTIFICATES_VIEW' => 'user-profile.certificates.view',
        'PROFILE_CERTIFICATES_CREATE' => 'user-profile.certificates.create',
        'PROFILE_CERTIFICATES_UPDATE' => 'user-profile.certificates.update',
        'PROFILE_CERTIFICATES_DELETE' => 'user-profile.certificates.delete',
        'PROFILE_WORK_LICENSE_VIEW' => 'user-profile.work-license.view',
        'PROFILE_WORK_LICENSE_UPDATE' => 'user-profile.work-license.update',

        // Company module permissions
        'COMPANY_VIEW' => 'companies.company.view',
        'COMPANY_LIST' => 'companies.company.list',
        'COMPANY_CREATE' => 'companies.company.create',
        'COMPANY_EDIT' => 'companies.company.update',
        'COMPANY_DELETE' => 'companies.company.delete',
//        'COMPANY_LOGIN_AS_ADMIN' => 'companies.company.login-as-admin',
        'COMPANY_EXPORT' => 'companies.company.export',

        // Role and Permission module permissions
        'ROLE_LIST' => 'settings.role.list',
        'ROLE_VIEW' => 'settings.role.view',
        'ROLE_CREATE' => 'settings.role.create',
        'ROLE_EDIT' => 'settings.role.update',
        'ROLE_DELETE' => 'settings.role.delete',

        'PERMISSION_LIST' => 'settings.permission.list',
        'PERMISSION_CREATE' => 'settings.permission.create',
        'PERMISSION_EDIT' => 'settings.permission.update',
        'PERMISSION_DELETE' => 'settings.permission.delete',
        'PERMISSION_VIEW' => 'settings.permission.view',
        'PERMISSION_ASSIGN' => 'settings.permission.update',
        'IDENTIFIER_LIST' => 'settings.identifier.list',
        'LOGIN_WAY_CREATE' => 'settings.login-way.create',
        'LOGIN_WAY_UPDATE' => 'settings.login-way.update',
        'LOGIN_WAY_VIEW' => 'settings.login-way.view',
        'LOGIN_WAY_DELETE' => 'settings.login-way.delete',
        'LOGIN_WAY_ACTIVATE' => 'settings.login-way.activate',
        'COMPANY_PROFILE_VIEW' => 'settings.company-profile.view',
        'DRIVER_VIEW' => 'settings.driver.view',
        'DRIVER_UPDATE' => 'settings.driver.update',

        // Organization module permissions
        'ORGANIZATION_BRANCH_VIEW' => 'organization.branch.view',
        'ORGANIZATION_BRANCH_CREATE' => 'organization.branch.create',
        'ORGANIZATION_BRANCH_UPDATE' => 'organization.branch.update',
        'ORGANIZATION_BRANCH_DELETE' => 'organization.branch.delete',
        'ORGANIZATION_MANAGEMENT_VIEW' => 'organization.management.view',
        'ORGANIZATION_MANAGEMENT_CREATE' => 'organization.management.create',
        'ORGANIZATION_MANAGEMENT_UPDATE' => 'organization.management.update',
        'ORGANIZATION_MANAGEMENT_DELETE' => 'organization.management.delete',
        'ORGANIZATION_USERS_VIEW' => 'organization.users.view',
        'ORGANIZATION_JOB_TITLE_VIEW' => 'organization.job-title.view',
        'ORGANIZATION_JOB_TITLE_CREATE' => 'organization.job-title.create',
        'ORGANIZATION_JOB_TITLE_UPDATE' => 'organization.job-title.update',
        'ORGANIZATION_JOB_TITLE_DELETE' => 'organization.job-title.delete',
        'ORGANIZATION_JOB_TITLE_LIST' => 'organization.job-title.list',
        'ORGANIZATION_JOB_TITLE_ACTIVATE' => 'organization.job-title.activate',
        'ORGANIZATION_JOB_TITLE_EXPORT' => 'organization.job-title.export',
        'ORGANIZATION_JOB_TYPE_VIEW' => 'organization.job-type.view',
        'ORGANIZATION_JOB_TYPE_CREATE' => 'organization.job-type.create',
        'ORGANIZATION_JOB_TYPE_UPDATE' => 'organization.job-type.update',
        'ORGANIZATION_JOB_TYPE_DELETE' => 'organization.job-type.delete',
        'ORGANIZATION_JOB_TYPE_LIST' => 'organization.job-type.list',
        'ORGANIZATION_JOB_TYPE_ACTIVATE' => 'organization.job-type.activate',
        'ORGANIZATION_JOB_TYPE_EXPORT' => 'organization.job-type.export',

        // Company Profile module permissions
        'COMPANY_PROFILE_OFFICIAL_DATA_UPDATE' => 'company-profile.official-data.update',
        'COMPANY_PROFILE_OFFICIAL_DATA_REQUEST_UPDATE' => 'company-profile.official-data.update',
        'COMPANY_PROFILE_LEGAL_DATA_UPDATE' => 'company-profile.legal-data.update',
        'COMPANY_PROFILE_LEGAL_DATA_CREATE' => 'company-profile.legal-data.create',
        'COMPANY_PROFILE_LEGAL_DATA_DELETE' => 'company-profile.legal-data.delete',
        'COMPANY_PROFILE_LEGAL_DATA_REQUEST_UPDATE' => 'company-profile.legal-data.update',
        'COMPANY_PROFILE_ADDRESS_UPDATE' => 'company-profile.address.update',
        'COMPANY_PROFILE_ADDRESS_REQUEST_UPDATE' => 'company-profile.address.update',
        'COMPANY_PROFILE_BRANCH_LIST' => 'company-profile.branch.list',
        'COMPANY_PROFILE_BRANCH_VIEW' => 'company-profile.branch.view',
        'COMPANY_PROFILE_OFFICIAL_DOCUMENT_CREATE' => 'company-profile.official-document.create',
        'COMPANY_PROFILE_OFFICIAL_DOCUMENT_UPDATE' => 'company-profile.official-document.update',
        'COMPANY_PROFILE_OFFICIAL_DOCUMENT_DELETE' => 'company-profile.official-document.delete',

        // Country module permissions
        'COUNTRY_VIEW' => 'country.country.view',
        'COUNTRY_LIST' => 'country.country.list',
        'COUNTRY_CREATE' => 'country.country.create',
        'COUNTRY_EDIT' => 'country.country.update',
        'COUNTRY_DELETE' => 'country.country.delete',
        'COUNTRY_EXPORT' => 'country.country.export',

        'STATE_VIEW' => 'country.state.view',
        'STATE_LIST' => 'country.state.list',
        'STATE_CREATE' => 'country.state.create',
        'STATE_EDIT' => 'country.state.update',
        'STATE_DELETE' => 'country.state.delete',
        'STATE_EXPORT' => 'country.state.export',

        'CITY_VIEW' => 'country.city.view',
        'CITY_LIST' => 'country.city.list',
        'CITY_CREATE' => 'country.city.create',
        'CITY_EDIT' => 'country.city.update',
        'CITY_DELETE' => 'country.city.delete',
        'CITY_EXPORT' => 'country.city.export',




    ]
];
