server {
    listen 80;
    server_name localhost;

    root /var/www/public;
    index index.php index.html;

    # Upload optimization
    client_body_buffer_size 10M;
    client_body_temp_path /tmp/nginx_upload;
    
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000; # PHP-FPM listens on port 9000
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;
        
        # PHP-FPM upload optimization
        fastcgi_buffering off;
        fastcgi_request_buffering off;
        fastcgi_read_timeout 300s;
        fastcgi_send_timeout 300s;
    }

    location ~ /\.ht {
        deny all;
    }
}
