<?php

declare(strict_types=1);

namespace Modules\Ecommerce\EcoOrder\DTO;

use Ramsey\Uuid\UuidInterface;

class CreateEcoOrderDTO
{
    public function __construct(
        public ?string $eco_client_id = null,
        public bool $is_guest = false,
        public ?string $client_type = null,
        public string $payment_status = 'unpaid',
        public string $order_status = 'pending',
        public ?string $payment_method = null,
        public ?string $transaction_ref = null,
        public ?string $payment_by = null,
        public ?string $payment_note = null,
        public float $order_amount = 0,
        public float $paid_amount = 0,
        public ?float $bring_change_amount = 0,
        public ?string $bring_change_amount_currency = null,
        public float $admin_commission = 0,
        public string $is_pause = '0',
        public ?string $cause = null,
        public ?string $shipping_address = null,
        public float $discount_amount = 0,
        public ?string $discount_type = null,
        public ?string $coupon_code = null,
        public string $coupon_discount_bearer = 'inhouse',
        public ?string $shipping_responsibility = null,
        public ?string $shipping_method_id = null,
        public float $shipping_cost = 0,
        public bool $is_shipping_free = false,
        public string $order_group_id = 'def-order-group',
        public string $verification_code = '0',
        public bool $verification_status = false,
        public ?array $shipping_address_data = null,
        public ?string $delivery_man_id = null,
        public float $deliveryman_charge = 0,
        public ?string $expected_delivery_date = null,
        public ?string $order_note = null,
        public ?string $billing_address = null,
        public ?array $billing_address_data = null,
        public string $order_type = 'default_type',
        public float $extra_discount = 0,
        public ?string $extra_discount_type = null,
        public float $refer_and_earn_discount = 0,
        public ?string $free_delivery_bearer = null,
        public bool $checked = false,
        public ?string $shipping_type = null,
        public ?string $delivery_type = null,
        public ?string $delivery_service_name = null,
        public ?string $third_party_delivery_tracking_id = null,
        public array $details = [],
    ) {
    }

    public function toArray(): array
    {
        return [
            'eco_client_id' => $this->eco_client_id,
            'is_guest' => $this->is_guest,
            'client_type' => $this->client_type,
            'payment_status' => $this->payment_status,
            'order_status' => $this->order_status,
            'payment_method' => $this->payment_method,
            'transaction_ref' => $this->transaction_ref,
            'payment_by' => $this->payment_by,
            'payment_note' => $this->payment_note,
            'order_amount' => $this->order_amount,
            'paid_amount' => $this->paid_amount,
            'bring_change_amount' => $this->bring_change_amount,
            'bring_change_amount_currency' => $this->bring_change_amount_currency,
            'admin_commission' => $this->admin_commission,
            'is_pause' => $this->is_pause,
            'cause' => $this->cause,
            'shipping_address' => $this->shipping_address,
            'discount_amount' => $this->discount_amount,
            'discount_type' => $this->discount_type,
            'coupon_code' => $this->coupon_code,
            'coupon_discount_bearer' => $this->coupon_discount_bearer,
            'shipping_responsibility' => $this->shipping_responsibility,
            'shipping_method_id' => $this->shipping_method_id,
            'shipping_cost' => $this->shipping_cost,
            'is_shipping_free' => $this->is_shipping_free,
            'order_group_id' => $this->order_group_id,
            'verification_code' => $this->verification_code,
            'verification_status' => $this->verification_status,
            'shipping_address_data' => $this->shipping_address_data,
            'delivery_man_id' => $this->delivery_man_id,
            'deliveryman_charge' => $this->deliveryman_charge,
            'expected_delivery_date' => $this->expected_delivery_date,
            'order_note' => $this->order_note,
            'billing_address' => $this->billing_address,
            'billing_address_data' => $this->billing_address_data,
            'order_type' => $this->order_type,
            'extra_discount' => $this->extra_discount,
            'extra_discount_type' => $this->extra_discount_type,
            'refer_and_earn_discount' => $this->refer_and_earn_discount,
            'free_delivery_bearer' => $this->free_delivery_bearer,
            'checked' => $this->checked,
            'shipping_type' => $this->shipping_type,
            'delivery_type' => $this->delivery_type,
            'delivery_service_name' => $this->delivery_service_name,
            'third_party_delivery_tracking_id' => $this->third_party_delivery_tracking_id,
            'details' => $this->details,
        ];
    }
}
