name: AI Code Reviewer

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: true
        type: number
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.ts'
      - '**.js'
      - '**.tsx'
      - '**.jsx'
      - '**.php'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AI Code Reviewer
        uses: New-Vision-2050/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "deepseek/deepseek-chat-v3-0324"
          exclude: "**/*.json, **/*.md, package-lock.json, yarn.lock, pnpm-lock.yaml, **/dist/**, **/build/**, **/.next/**, **/node_modules/**, **/vendor/**, **/storage/**"
          PR_NUMBER: ${{ github.event.inputs.pr_number || github.event.number }}
